$schema: https://json.schemastore.org/eslintrc.json
extends:
  - "@antfu"
plugins:
  - jsdoc
rules:
  vue/max-attributes-per-line: error
  function-paren-newline:
    - error
    - minItems: 2
  function-call-argument-newline:
    - error
    - consistent
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 2
  prefer-template: error
  no-console: warn
