/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MenuBar: typeof import('./components/MenuBar.vue')['default']
    SlideNav: typeof import('./components/SlideNav.vue')['default']
    StorySlider: typeof import('./components/StorySlider/index.vue')['default']
    StorySliderSlide: typeof import('./components/StorySlider/Slide.vue')['default']
    TimeAxis: typeof import('./components/TimeAxis/index.vue')['default']
    TimeAxisTick: typeof import('./components/TimeAxis/Tick.vue')['default']
    TimeEra: typeof import('./components/TimeEra.vue')['default']
    Timeline: typeof import('./components/Timeline.vue')['default']
    TimeMarker: typeof import('./components/TimeMarker.vue')['default']
    TimeNav: typeof import('./components/TimeNav.vue')['default']
  }
}
