/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    FontAwesomeIcon: typeof import('@fortawesome/vue-fontawesome')['FontAwesomeIcon']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./src/components/Slide/Index.vue')['default']
    SlideNav: typeof import('./src/components/Slide/Nav.vue')['default']
    StorySlider: typeof import('./src/components/StorySlider.vue')['default']
    StorySliderSlide: typeof import('./src/components/StorySlider/Slide.vue')['default']
    StorySliderSlideNav: typeof import('./src/components/StorySlider/SlideNav.vue')['default']
    TimeAxis: typeof import('./src/components/TimeAxis/index.vue')['default']
    TimeAxisMarker: typeof import('./src/components/TimeAxis/Marker.vue')['default']
    TimeAxisTick: typeof import('./src/components/TimeAxis/Tick.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    TimeNav: typeof import('./src/components/TimeNav.vue')['default']
    TimeNavTimeAxis: typeof import('./src/components/TimeNav/TimeAxis/index.vue')['default']
    TimeNavTimeAxisMarker: typeof import('./src/components/TimeNav/TimeAxis/Marker.vue')['default']
    TimeNavTimeAxisTick: typeof import('./src/components/TimeNav/TimeAxis/Tick.vue')['default']
    TimeNavTimeEra: typeof import('./src/components/TimeNav/TimeEra.vue')['default']
    UseDraggable: typeof import('@vueuse/components')['UseDraggable']
  }
}
