/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FontAwesomeIcon: typeof import('@fortawesome/vue-fontawesome')['FontAwesomeIcon']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    StorySlider: typeof import('./src/components/StorySlider/index.vue')['default']
    StorySliderSlide: typeof import('./src/components/StorySlider/Slide.vue')['default']
    StorySliderSlideNav: typeof import('./src/components/StorySlider/SlideNav.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    TimeNav: typeof import('./src/components/TimeNav/index.vue')['default']
    TimeNavTimeAxis: typeof import('./src/components/TimeNav/TimeAxis/index.vue')['default']
    TimeNavTimeAxisMarker: typeof import('./src/components/TimeNav/TimeAxis/Marker.vue')['default']
    TimeNavTimeAxisTick: typeof import('./src/components/TimeNav/TimeAxis/Tick.vue')['default']
    TimeNavTimeEra: typeof import('./src/components/TimeNav/TimeEra.vue')['default']
  }
}
